import numpy as np
import ROOT as rt

sample_configurables = {
'SMS-T2bW' : {
  'legend' : 'SMS-T2bW',
  'color'  : rt.kViolet,
  'style'  : 1,
  'width'  : 2,
  'fill'  : None,
  'fill_style'  : None,
             },
'SMS-T2-4bd_490' : {
  'legend' : 'SMS-T2-4bd',
  'color'  : rt.kViolet-5,
  'style'  : 1,
  'width'  : 2,
  'fill'  : None,
  'fill_style'  : None,
             },
'SMS-T2-4bd_490_I' : {
  'legend' : 'SMS-T2-4bd I',
  'color'  : rt.kViolet-5,
  'style'  : 1,
  'width'  : 2,
  'fill'  : None,
  'fill_style'  : None,
             },
'SMS-T2-4bd_490_IV' : {
  'legend' : 'SMS-T2-4bd IV',
  'color'  : rt.kViolet-8,
  'style'  : 1,
  'width'  : 2,
  'fill'  : None,
  'fill_style'  : None,
             },
'SMS-T2-4bd_420' : {
  'legend' : 'SMS-T2-4bd',
  'color'  : rt.kViolet+5,
  'style'  : 1,
  'width'  : 2,
  'fill'  : None,
  'fill_style'  : None,
             },
'TTJets_2017'   : {
  'legend' : 't#bar{t}+jets',
  'color'  : 26,
  'style'  : 1,
  'width'  : 3,
  'fill'   : 26,
  'fill_style'   : 1001,
             },
'WJets_2017'   : {
  'legend' : 'W+jets',
  'color'  : 36,
  'style'  : 1,
  'width'  : 3,
  'fill'   : 36,
  'fill_style'   : 1001,
             },
'ST'   : {
  'legend' : 'Single Top',
  'color'  : 46,
  'style'  : 1,
  'width'  : 3,
  'fill'   : 46,
  'fill_style'   : 1001,
             },
'WW_2017'   : {
  'legend' : 'WW',
  'color'  : 46,
  'style'  : 1,
  'width'  : 3,
  'fill'   : 46,
  'fill_style'   : 1001,
             },
'ZZ_2017'   : {
  'legend' : 'ZZ',
  'color'  : 46,
  'style'  : 1,
  'width'  : 3,
  'fill'   : 46,
  'fill_style'   : 1001,
             },
}

######   configuration template   ######
"""
'Null'    : {
  'xlabel'  : None,
  'ylabel'  : None,
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
"""
######  end template  ######
plot_configurables = {
#'S_jet_pt'    : {
#  'xlabel'  : 'S jet p_{T}',
#  'ylabel'  : 'jets',
#  'nbins_x' : None,
#  'xmin'    : None,
#  'xmax'    : None,
#  'nbinsy'  : None,
#  'ymin'    : None,
#  'ymax'    : None,
#  'log'     : False,
#              },
#'ISR_jet_pt'    : {
#  'xlabel'  : 'ISR jet p_{T}',
#  'ylabel'  : 'jets',
#  'nbins_x' : None,
#  'xmin'    : None,
#  'xmax'    : None,
#  'nbinsy'  : None,
#  'ymin'    : None,
#  'ymax'    : None,
#  'log'     : False,
#              },
'Mu_PT_SV'    : {
  'xlabel'  : 'p_{T} SVs',
  'ylabel'  : 'Events',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'Mu_NSV'    : {
  'xlabel'  : 'Mu_N SVs',
  'ylabel'  : 'Events',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'Mu_MLL'    : {
  'xlabel'  : 'Mu_M_{ll}',
  'ylabel'  : 'Events',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'Mu_MS'    : {
  'xlabel'  : 'Mu_M_{S}',
  'ylabel'  : 'Events',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'Mu_PS'    : {
  'xlabel'  : 'p^{S}',
  'ylabel'  : 'Events',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'Mu_PTS'    : {
  'xlabel'  : 'p_{T}^{S}',
  'ylabel'  : 'Events',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'Mu_PzS'    : {
  'xlabel'  : 'p_{z}^{S}',
  'ylabel'  : 'Events',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'Mu_PTS_div_MS'    : {
  'xlabel'  : 'p_{T}^{S} / (p_{T}^{S} + M_{S})',
  'ylabel'  : 'Events',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'Mu_PzS_div_MS'    : {
  'xlabel'  : 'p_{z}^{S} / (p_{z}^{S} + M_{S})',
  'ylabel'  : 'Events',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'Mu_NSV_NBjets'    : {
  'xlabel'  : 'Mu_N SVs',
  'ylabel'  : 'Mu_N b jets',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'Mu_NsSV_Nsj'    : {
  'xlabel'  : 'Mu_N S SVs',
  'ylabel'  : 'Mu_N S jets',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'Mu_NisrSV_Nisrj'    : {
  'xlabel'  : 'Mu_N ISR SVs',
  'ylabel'  : 'Mu_N ISR jets',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'Mu_MS_PzS'    : {
  'xlabel'  : 'Mu_M_{S}',
  'ylabel'  : 'p_{z}^{S}',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'Mu_MS_PTS'    : {
  'xlabel'  : 'Mu_M_{S}',
  'ylabel'  : 'p_{T}^{S}',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'Mu_MS_dphiLepMET'    : {
  'xlabel'  : 'Mu_M_{S}',
  'ylabel'  : '#Delta #phi(lep, E_{T}^{miss})',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'Mu_MS_RISR'    : {
  'xlabel'  : 'Mu_M_{S}',
  'ylabel'  : 'R_{ISR}',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'Mu_MS_PTISR'    : {
  'xlabel'  : 'Mu_M_{S}',
  'ylabel'  : 'p_{T}^{ISR}',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'Mu_dphi_lep_MET'    : {
  'xlabel'  : '#Delta #phi(lep, E_{T}^{miss})',
  'ylabel'  : 'Events',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'Mu_dphiCMI'    : {
  'xlabel'  : '#Delta #phi_{CMI}',
  'ylabel'  : 'Events',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'Mu_dphiSI'    : {
  'xlabel'  : '#Delta #phi_{SI}',
  'ylabel'  : 'Events',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'El_PT_SV'    : {
  'xlabel'  : 'p_{T} SVs',
  'ylabel'  : 'Events',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'El_NSV'    : {
  'xlabel'  : 'El_N SVs',
  'ylabel'  : 'Events',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'El_MLL'    : {
  'xlabel'  : 'El_M_{ll}',
  'ylabel'  : 'Events',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'El_MS'    : {
  'xlabel'  : 'El_M_{S}',
  'ylabel'  : 'Events',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'El_PS'    : {
  'xlabel'  : 'p^{S}',
  'ylabel'  : 'Events',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'El_PTS'    : {
  'xlabel'  : 'p_{T}^{S}',
  'ylabel'  : 'Events',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'El_PzS'    : {
  'xlabel'  : 'p_{z}^{S}',
  'ylabel'  : 'Events',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'El_PTS_div_MS'    : {
  'xlabel'  : 'p_{T}^{S} / (p_{T}^{S} + M_{S})',
  'ylabel'  : 'Events',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'El_PzS_div_MS'    : {
  'xlabel'  : 'p_{z}^{S} / (p_{z}^{S} + M_{S})',
  'ylabel'  : 'Events',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'El_NSV_NBjets'    : {
  'xlabel'  : 'El_N SVs',
  'ylabel'  : 'El_N b jets',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'El_NsSV_Nsj'    : {
  'xlabel'  : 'El_N S SVs',
  'ylabel'  : 'El_N S jets',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'El_NisrSV_Nisrj'    : {
  'xlabel'  : 'El_N ISR SVs',
  'ylabel'  : 'El_N ISR jets',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'El_MS_PzS'    : {
  'xlabel'  : 'El_M_{S}',
  'ylabel'  : 'p_{z}^{S}',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'El_MS_PTS'    : {
  'xlabel'  : 'El_M_{S}',
  'ylabel'  : 'p_{T}^{S}',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'El_MS_dphiLepMET'    : {
  'xlabel'  : 'El_M_{S}',
  'ylabel'  : '#Delta #phi(lep, E_{T}^{miss})',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'El_MS_RISR'    : {
  'xlabel'  : 'El_M_{S}',
  'ylabel'  : 'R_{ISR}',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'El_MS_PTISR'    : {
  'xlabel'  : 'El_M_{S}',
  'ylabel'  : 'p_{T}^{ISR}',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'El_dphi_lep_MET'    : {
  'xlabel'  : '#Delta #phi(lep, E_{T}^{miss})',
  'ylabel'  : 'Events',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'El_dphiCMI'    : {
  'xlabel'  : '#Delta #phi_{CMI}',
  'ylabel'  : 'Events',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'El_dphiSI'    : {
  'xlabel'  : '#Delta #phi_{SI}',
  'ylabel'  : 'Events',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
}
msab_vars = {
'MSa_min_MSb_div_MSaMSb'    : {
  'xlabel'  : '(M_{Sa} - M_{Sb}) / (M_{Sa} + M_{Sb})',
  'ylabel'  : 'Events',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'avg_MSab'    : {
  'xlabel'  : '(M_{Sa} - M_{Sb}) / mean(M_{Sa}, M_{Sb})',
  'ylabel'  : 'Events',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'MSab'    : {
  'xlabel'  : 'M_{Sa}',
  'ylabel'  : 'M_{Sb}',
  'nbins_x' : None,
  'xmin'    : 0,
  'xmax'    : 300,
  'nbinsy'  : None,
  'ymin'    : 0,
  'ymax'    : 300,
  'log'     : True,
              },
'MVab'    : {
  'xlabel'  : 'M_{Va}',
  'ylabel'  : 'M_{Vb}',
  'nbins_x' : None,
  'xmin'    : 0,
  'xmax'    : 120,
  'nbinsy'  : None,
  'ymin'    : 0,
  'ymax'    : 120,
  'log'     : True,
              },
'EVab'    : {
  'xlabel'  : 'E_{Va}',
  'ylabel'  : 'E_{Vb}',
  'nbins_x' : None,
  'xmin'    : 0,
  'xmax'    : 120,
  'nbinsy'  : None,
  'ymin'    : 0,
  'ymax'    : 120,
  'log'     : True,
              },
'MSab_diff_MVab'    : {
  'xlabel'  : 'M_{Sa} - M_{Va}',
  'ylabel'  : 'M_{Sb} - M_{Vb}',
  'nbins_x' : None,
  'xmin'    : 0,
  'xmax'    : 300,
  'nbinsy'  : None,
  'ymin'    : 0,
  'ymax'    : 300,
  'log'     : True,
              },
'MS_diff'    : {
  'xlabel'  : 'M_{Sa} - M_{Sb}',
  'ylabel'  : 'events',
  'nbins_x' : None,
  'xmin'    : 0,
  'xmax'    : 300,
  'nbinsy'  : None,
  'ymin'    : 0,
  'ymax'    : 300,
  'log'     : True,
              },
'MV_diff'    : {
  'xlabel'  : 'M_{Va} - M_{Vb}',
  'ylabel'  : 'events',
  'nbins_x' : None,
  'xmin'    : 0,
  'xmax'    : 300,
  'nbinsy'  : None,
  'ymin'    : 0,
  'ymax'    : 300,
  'log'     : True,
              },
}
plot_configurables_old = {
'PT_lep'    : {
  'xlabel'  : 'lep p_{T} [GeV]',
  'ylabel'  : 'leps',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'PT_s_lep'    : {
  'xlabel'  : 's lep p_{T} [GeV]',
  'ylabel'  : 's leps',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'PT_isr_lep'    : {
  'xlabel'  : 'isr lep p_{T} [GeV]',
  'ylabel'  : 'isr leps',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'PT_jet'    : {
  'xlabel'  : 'jet p_{T} [GeV]',
  'ylabel'  : 'jets',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'PT_s_jet'    : {
  'xlabel'  : 's jet p_{T} [GeV]',
  'ylabel'  : 's jets',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'PT_isr_jet'    : {
  'xlabel'  : 'isr jet p_{T} [GeV]',
  'ylabel'  : 'isr jets',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'loose_PT_jet'    : {
  'xlabel'  : 'loose b jet p_{T} [GeV]',
  'ylabel'  : 'loose b jets',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'medium_PT_jet'    : {
  'xlabel'  : 'medium b jet p_{T} [GeV]',
  'ylabel'  : 'medium b jets',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'tight_PT_jet'    : {
  'xlabel'  : 'tight b jet p_{T} [GeV]',
  'ylabel'  : 'tight b jets',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'ptisr'    : {
  'xlabel'  : 'p_{T}^{ISR} [GeV]',
  'ylabel'  : 'events',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'ptcm'    : {
  'xlabel'  : 'p_{T}^{CM} [GeV]',
  'ylabel'  : 'events',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'Lep_to_Lep'    : {
  'xlabel'  : '2 leptons',
  'ylabel'  : '2 opp leptons',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'Lep_to_Charge'    : {
  'xlabel'  : 'Lepton flavor',
  'ylabel'  : 'Lepton Charge',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'MET'    : {
  'xlabel'  : 'E_{T}^{miss} [GeV]',
  'ylabel'  : 'Events',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'S_Flavor_jet'    : {
  'xlabel'  : 'S jet Flavor',
  'ylabel'  : 'jets',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'S_Flavor_lep'    : {
  'xlabel'  : 'S lep Flavor',
  'ylabel'  : 'leps',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'ISR_Flavor_jet'    : {
  'xlabel'  : 'ISR jet Flavor',
  'ylabel'  : 'jets',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'ISR_Flavor_lep'    : {
  'xlabel'  : 'ISR lep Flavor',
  'ylabel'  : 'leps',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'S_ISR_N_lep'    : {
  'xlabel'  : 'N S leptons',
  'ylabel'  : 'N ISR leptons',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'S_ISR_N_jet'    : {
  'xlabel'  : 'N S jets',
  'ylabel'  : 'N ISR jets',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'S_ISR_N_loose_jet'    : {
  'xlabel'  : 'N S loose b-jets',
  'ylabel'  : 'N ISR loose b-jets',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'S_ISR_N_medium_jet'    : {
  'xlabel'  : 'N S medium b-jets',
  'ylabel'  : 'N ISR medium b-jets',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'S_ISR_N_tight_jet'    : {
  'xlabel'  : 'N S tight b-jets',
  'ylabel'  : 'N ISR tight b-jets',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'RISR_N_lep'    : {
  'xlabel'  : 'R_{ISR}',
  'ylabel'  : 'N leptons',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : 0.,
  'ymax'    : 3.,
  'log'     : False,
              },
'RISR_N_jet'    : {
  'xlabel'  : 'R_{ISR}',
  'ylabel'  : 'N jets',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : 0.,
  'ymax'    : 15.,
  'log'     : False,
              },
'RISR_N_S_lep'    : {
  'xlabel'  : 'R_{ISR}',
  'ylabel'  : 'N S leptons',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : 0.,
  'ymax'    : 3.,
  'log'     : False,
              },
'RISR_N_S_jet'    : {
  'xlabel'  : 'R_{ISR}',
  'ylabel'  : 'N S jets',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : 0.,
  'ymax'    : 15.,
  'log'     : False,
              },
'RISR_N_ISR_lep'    : {
  'xlabel'  : 'R_{ISR}',
  'ylabel'  : 'N ISR leptons',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : 0.,
  'ymax'    : 3.,
  'log'     : False,
              },
'RISR_N_ISR_jet'    : {
  'xlabel'  : 'R_{ISR}',
  'ylabel'  : 'N ISR jets',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : 0.,
  'ymax'    : 15.,
  'log'     : False,
              },
'PTISR_N_lep'    : {
  'xlabel'  : 'P_{T}^{ISR}',
  'ylabel'  : 'N leptons',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : 0.,
  'ymax'    : 3.,
  'log'     : False,
              },
'PTISR_N_jet'    : {
  'xlabel'  : 'P_{T}^{ISR}',
  'ylabel'  : 'N jets',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : 0.,
  'ymax'    : 15.,
  'log'     : False,
              },
'PTISR_N_S_lep'    : {
  'xlabel'  : 'P_{T}^{ISR}',
  'ylabel'  : 'N S leptons',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : 0.,
  'ymax'    : 15.,
  'log'     : False,
              },
'PTISR_N_S_jet'    : {
  'xlabel'  : 'P_{T}^{ISR}',
  'ylabel'  : 'N S jets',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : 0.,
  'ymax'    : 15.,
  'log'     : False,
              },
'PTISR_N_ISR_lep'    : {
  'xlabel'  : 'P_{T}^{ISR}',
  'ylabel'  : 'N ISR leptons',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : 0.,
  'ymax'    : 3.,
  'log'     : False,
              },
'PTISR_N_ISR_jet'    : {
  'xlabel'  : 'P_{T}^{ISR}',
  'ylabel'  : 'N ISR jets',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : 0.,
  'ymax'    : 15.,
  'log'     : False,
              },
'PTCM_N_lep'    : {
  'xlabel'  : 'P_{T}^{CM}',
  'ylabel'  : 'N leptons',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : 0.,
  'ymax'    : 3.,
  'log'     : False,
              },
'PTCM_N_jet'    : {
  'xlabel'  : 'P_{T}^{CM}',
  'ylabel'  : 'N jets',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : 0.,
  'ymax'    : 15.,
  'log'     : False,
              },
'PTCM_N_S_lep'    : {
  'xlabel'  : 'P_{T}^{CM}',
  'ylabel'  : 'N S leptons',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : 0.,
  'ymax'    : 3.,
  'log'     : False,
              },
'PTCM_N_S_jet'    : {
  'xlabel'  : 'P_{T}^{CM}',
  'ylabel'  : 'N S jets',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : 0.,
  'ymax'    : 15.,
  'log'     : False,
              },
'PTCM_N_ISR_lep'    : {
  'xlabel'  : 'P_{T}^{CM}',
  'ylabel'  : 'N ISR leptons',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : 0.,
  'ymax'    : 3.,
  'log'     : False,
              },
'PTCM_N_ISR_jet'    : {
  'xlabel'  : 'P_{T}^{CM}',
  'ylabel'  : 'N ISR jets',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : 0.,
  'ymax'    : 15.,
  'log'     : False,
              },
'risr'    : {
  'xlabel'  : 'R_{ISR}',
  'ylabel'  : 'events',
  'nbins_x' : None,
  'xmin'    : 0.,
  'xmax'    : 1.,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'RISR_PTISR'    : {
  'xlabel'  : 'R_{ISR}',
  'ylabel'  : 'p_{T}^{ISR} [GeV]',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'RISR_PTCM'    : {
  'xlabel'  : 'R_{ISR}',
  'ylabel'  : 'p_{T}^{CM} [GeV]',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'PTISR_PTCM'    : {
  'xlabel'  : 'p_{T}^{ISR}',
  'ylabel'  : 'p_{T}^{CM} [GeV]',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'dphi_PTCM'    : {
  'xlabel'  : '#Delta #phi',
  'ylabel'  : 'p_{T}^{CM} [GeV]',
  'nbins_x' : None,
  'xmin'    : 0,
  'xmax'    : np.pi,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'dphi_PTCM_div_PTISR'    : {
  'xlabel'  : '#Delta #phi',
  'ylabel'  : 'p_{T}^{CM} / p_{T}^{ISR}',
  'nbins_x' : None,
  'xmin'    : 0,
  'xmax'    : np.pi,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'N_PT_loose_jet'    : {
  'xlabel'  : 'N loose b jets',
  'ylabel'  : 'p_{T} loose b jets',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'N_PT_medium_jet'    : {
  'xlabel'  : 'N medium b jets',
  'ylabel'  : 'p_{T} medium b jets',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'N_PT_tight_jet'    : {
  'xlabel'  : 'N tight b jets',
  'ylabel'  : 'p_{T} tight b jets',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'N_PT_lep'    : {
  'xlabel'  : 'N leps',
  'ylabel'  : 'p_{T} leps',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },

}
